### ISSUE TITLE
PANIC GUI and Elettra Alarm server

### ISSUE THREAD

**Issue by almarass** [tango-controls/PANIC#22]
Can PANIC GUI be used to visualize existing alarms with an Elettra Alarm Server?

Thanks
Alex

**Comment by sergirubio** [comment]
Yes, but using the latest versions of each.

G.Scalamera from Elettra did it just 2 weeks ago

Sergi

**Comment by almarass** [comment]
Is 6.4.0 the last version of PANIC GUI?

Thanks,
Alex

2018-06-13 12:52 GMT+02:00 sergirubio <notifications@github.com>:

**Comment by sergirubio** [comment]
Hi,

Sorry, it is 6.5.1 ; download it from github or PIP:

https://github.com/tango-controls/PANIC/releases/tag/6.5.1

https://pypi.org/project/panic/


Elettra already had both systems running together, you can contact
Graziano Scalamera (graziano.scalamera@elettra.trieste.it) and ask him if
he had to change something in the GUI.

Sorry for the late answer (I'm on medical leave)

Sergi

**Comment by almarass** [comment]
Hi,
I installed version 6.5.1 and tried to use PANIC GUI together with an
Elettra Alarm handler (server).
Apparently it does nothing.

Then, in order to test my PANIC installation, I tried to follow the
instructions at:
https://pythonhosted.org/panic/recipes/InstallPanic.html#id3
involving PyAlarm.py and PySignalSimulator.py.

I could find PyAlarm.py, but not PySignalSimulator.py.
I have further googled, but with no result (
https://tango-ds.svn.sourceforge.net/svnroot/tango-ds/DeviceClasses/Simulators/PySignalSimulator/trunk
PySignalSimulator not active)

How may I proceed?

Thanks,
Alex

2018-06-14 11:44 GMT+02:00 sergirubio <notifications@github.com>:

**Comment by sergirubio** [comment]
Hi,

The PySignalSimulator was renamed to SimulatorDS, sorry

https://github.com/tango-controls/SimulatorDS

**Comment by almarass** [comment]
Hi,
I have used SimulatorDS to test my installation and it seems to work (see
attached screenshot).

If I try to use PANIC GUI towards a remote machine running the last version
of Elettra Alarm handler, is it enough to set my TANGO_HOST variable or am
I to set something else before running PANIC GUI?

Thanks,
Alex


2018-06-14 20:22 GMT+02:00 sergirubio <notifications@github.com>:

**Comment by sergirubio** [comment]
Hi Alex,

I'm still on leave so I add Graziano in CC in case to know if he had to do
any change on the GUI side.


Sergi Rubio

**Comment by gscalam** [comment]
Hi,
at the moment the GUI or the AlarmHandler need some tricks.
On the AlarmHandler side you can:
 - rename the Tango Class Name from AlarmHandler to PyAlarm in ClassFactory.cpp
 - manually modify after the device server is started the device property AlarmList in order to be an array of "tag_name: tag_formula" instead of only tag names. The same result could be reached modifying "void AlarmHandler::put_signal_property()" so that the device property is stored in the right format and no manual operation is needed.

Graziano

**Comment by adityadangeska** [comment]
Hi Team,

I am facing issue integrating PANIC GUI with Elettra AlarmHandler server. Details of the issue can be found in the below TANGO forum post:

http://www.tango-controls.org/community/forum/c/general/development/elettra-alarmhandler-crash/

Please guide further.

- Aditya

**Comment by sergirubio** [comment]
Hi Aditya, Graziano

In principle, it should not be needed to rename the AlarmHandler to 
PyAlarm; Panic should be able to connect to the AlarmHandler anyway.

Init() is executed because it is the default way to reload properties on 
PyAlarm; in the case of AlarmHandler I can do a restart using Starter if 
this solution is fine for you.

If this solution is fine I can upload a patch,

Sergi

**Comment by sergirubio** [comment]
I just pushed the changes to develop so you can test them

Sergi

**Comment by sergirubio** [comment]
the project has been moved to gitlab and the work will continue there, I'm actually reviewing all issues and it should be fixed soon

https://gitlab.com/tango-controls/panic/-/issues?sort=created_date&state=opened

if you have a gitlab user, just make a comment on your issue and I'll try to link it back to you
